{
 "title": "Hoprd Node",
 "description": "Metrics for Hoprd nodes",
 "tags": [
  "hopr",
  "Home"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "canvas",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "targets": [
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hoprd_mgauge_version", "legendFormat": "{{version}}" }
   ]
  },
  {
   "title": "Network",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    { "expr": "hoprd_mgauge_version", "legendFormat": "{{hoprd_network}}" }
   ]
  },
  {
   "title": "Network Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "core_gauge_network_health", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Up time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hoprd_gauge_startup_unix_time_seconds*1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nº restarts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(changes(hoprd_gauge_startup_unix_time_seconds[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Used",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (irate(node_cpu_seconds_total{mode!~\"idle\"}[$__rate_interval])) / sum ((irate(node_cpu_seconds_total[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemFree_bytes - (node_memory_Cached_bytes + node_memory_Buffers_bytes + node_memory_SReclaimable_bytes))/node_memory_MemTotal_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Opened channels",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(core_counter_strategy_promiscuous_opened_channels[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Close channels",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(core_counter_strategy_promiscuous_closed_channels[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Incoming channels",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(core_gauge_num_incoming_channels) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outgoing channels",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(core_gauge_num_outgoing_channels)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "High Quality Peers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(core_mgauge_peers_by_quality{quality=\"high\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Low quality peers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(core_mgauge_peers_by_quality{quality=\"low\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total messages sent",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(core_counter_sent_messages[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total failed messages sent",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(core_counter_failed_send_messages[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total messages received",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(core_counter_received_messages[$__range])",
     "legendFormat": "Received"
    }
   ]
  },
  {
   "title": "Total messages forwarded",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(core_counter_forwarded_messages[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nº message sent per minute",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(core_counter_sent_messages[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nº messages failed sent per minute",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(core_counter_failed_send_messages[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nº messages received per minute",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(core_counter_received_messages[1m])",
     "legendFormat": "Received"
    }
   ]
  },
  {
   "title": "Nº messages forwarded per minute",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(core_counter_forwarded_messages[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redeemed tickets",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(core_ethereum_counter_indexer_tickets_redeemed[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Losing tickets",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(core_counter_losing_tickets[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Created tickets",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(core_counter_created_tickets[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Winning tickets",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(core_ethereum_counter_winning_tickets[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ticket probability",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(core_ethereum_counter_winning_tickets[$__range]) / increase(core_counter_received_messages[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Agregated tickets",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(core_counter_aggregated_tickets[$__range])",
     "legendFormat": "Agregated"
    }
   ]
  },
  {
   "title": "Performed ticket aggregations",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(core_counter_aggregations[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Messages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Message latency (ms)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(hoprd_histogram_message_latency_ms_bucket[$__range])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Messages latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(hoprd_histogram_message_latency_ms_sum[$__rate_interval]) \n/\nrate(hoprd_histogram_message_latency_ms_count[$__rate_interval]) > 0    \n",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Message rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "rate(core_counter_received_messages[$__rate_interval])",
     "legendFormat": "Received"
    },
    {
     "expr": "rate(core_counter_sent_messages[$__rate_interval])",
     "legendFormat": "Sent"
    },
    {
     "expr": "rate(core_counter_forwarded_messages[$__rate_interval])",
     "legendFormat": "Forwarded"
    },
    {
     "expr": "rate(core_counter_failed_send_messages[$__rate_interval])",
     "legendFormat": "Failed sent"
    }
   ]
  },
  {
   "title": "Message latency quantiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(hoprd_histogram_message_latency_ms_bucket[$__rate_interval])))",
     "legendFormat": "Quantile 50%"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(hoprd_histogram_message_latency_ms_bucket[10m])))",
     "legendFormat": "Quantile 90%"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(hoprd_histogram_message_latency_ms_bucket[10m])))",
     "legendFormat": "Quantile 95%"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (job, le) (rate(hoprd_histogram_message_latency_ms_bucket{job=~\"${pod_name}\"}[10m])))",
     "legendFormat": "Quantile 99%"
    }
   ]
  },
  {
   "title": "Failed messages sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "increase(core_counter_failed_send_messages[$__rate_interval])",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Message path length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "expr": "rate(core_histogram_path_length_sum[$__rate_interval])\n/\nrate(core_histogram_path_length_count[$__rate_interval])",
     "legendFormat": "Hops"
    }
   ]
  },
  { "title": "Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Network health",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    { "expr": "avg(core_gauge_network_health)", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Peers by quality",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "sum by(quality) (core_mgauge_peers_by_quality{quality=\"high\"})",
     "legendFormat": "High quality peers - {{job}}"
    },
    {
     "expr": "sum by(quality) (core_mgauge_peers_by_quality{quality=\"low\"})",
     "legendFormat": "Low quality peers - {{job}}"
    }
   ]
  },
  {
   "title": "Heartbeat response time (sec)",
   "type": "bargauge",
   "description": "Measures total time it takes to probe other nodes (in seconds)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(core_histogram_heartbeat_time_seconds_bucket[$__range])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Heartbeat pings rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(core_counter_heartbeat_successful_pings[$__rate_interval])",
     "legendFormat": "Succeed - {{job}}"
    },
    {
     "expr": "increase(core_counter_heartbeat_failed_pings[$__rate_interval])",
     "legendFormat": "Failed - {{job}}"
    }
   ]
  },
  {
   "title": "Ping response time (sec)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(core_histogram_ping_time_seconds_bucket[$__range])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Ethereum Transaction calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "targets": [
    {
     "expr": "increase(core_ethereum_counter_num_send_transactions[$__rate_interval])",
     "legendFormat": "Txs calls"
    }
   ]
  },
  {
   "title": "Opened channels",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "sum by (counterparty,direction) (core_mgauge_channel_balances)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "System metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  {
   "title": "CPU Basic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * sum by(job) (irate(node_cpu_seconds_total{mode!=\"idle\"}[$__rate_interval])) / on(job) group_left sum by (job)((irate(node_cpu_seconds_total[$__rate_interval])))",
     "legendFormat": "% Cpu usage"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "RAM Total - {{job}}" },
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemFree_bytes - (node_memory_Cached_bytes + node_memory_Buffers_bytes + node_memory_SReclaimable_bytes)",
     "legendFormat": "RAM used - {{job}}"
    },
    {
     "expr": "node_memory_Cached_bytes + node_memory_Buffers_bytes + node_memory_SReclaimable_bytes",
     "legendFormat": "RAM Cache + Buffer- {{job}}"
    }
   ]
  },
  {
   "title": "Bytes of used heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(hoprd_gauge_nodejs_total_used_heap_bytes) by (job)",
     "legendFormat": "Used heap - {{job}}"
    },
    {
     "expr": "avg(avg_over_time(hoprd_gauge_nodejs_total_used_heap_bytes[1h])) by (job)",
     "legendFormat": "Used heap (moving avg over 1h) - {{job}}"
    }
   ]
  },
  {
   "title": "Bytes of total available heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(hoprd_gauge_nodejs_total_available_heap_bytes) by (job)",
     "legendFormat": "Total available heap - {{job}}"
    },
    {
     "expr": "avg(avg_over_time(hoprd_gauge_nodejs_total_available_heap_bytes[1h])) by (job)",
     "legendFormat": "Total available heap (moving avg over 1h) - {{job}}"
    }
   ]
  }
 ]
}