---
#################################################################################
# Automatic pipeline that triggers the update of the SDK Python
#################################################################################
name: SDK Python

on:
  workflow_call:
    inputs:
      base_branch:
        required: true
        type: string


concurrency:
  group: sdk-python
  cancel-in-progress: true

jobs:
  sdk-python:
    name: SDK Python
    runs-on: ubuntu-2-core
    steps:
      - name: Checkout hoprnet repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.base_branch }}

      - name: Sccache Setup
        uses: mozilla-actions/sccache-action@v0.0.3
        with:
          version: "v0.4.0"

      - name: Install Nix
        uses: cachix/install-nix-action@v24
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Nix Cache
        uses: cachix/cachix-action@v13
        with:
          name: hoprnet
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        continue-on-error: true

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(pwd)/.yarn/cache" >> $GITHUB_OUTPUT

      - name: Restore yarn cache
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Restore cargo cache
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock', 'rust-toolchain.toml') }}
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            .cargo/.package-cache/

      # Doing the checkout after restoring the cache
      - name: Checkout hoprd-python-sdk repository
        uses: actions/checkout@v4
        with:
          repository: hoprnet/hoprd-sdk-python
          path: "./hoprd-sdk-python"
          token: ${{ secrets.GH_RUNNER_TOKEN }}
          ref: ${{ inputs.base_branch }}

      - name: Setup
        id: setup
        run: |
          export current_version=$(./scripts/get-current-version.sh docker)
          echo "current_version=${current_version}" >> $GITHUB_OUTPUT
          export open_api_spec="https://raw.githubusercontent.com/hoprnet/hoprnet/${{ inputs.base_branch }}/packages/hoprd/rest-api-v3-spec.yaml"
          yq -iP '.specURL=env(open_api_spec)' -o json scripts/python-sdk-config.json
          yq -iP '.options.additionalProperties.packageVersion=env(current_version)' -o json scripts/python-sdk-config.json

      - name: Generate Docs
        run: |
          nix develop -c make build-docs-api

      - name: Generate SDK Python
        run: |
          curl -X POST https://generator3.swagger.io/api/generate -H 'content-type: application/json' -d @scripts/python-sdk-config.json --output hoprd-sdk-python.zip
          sleep 999999999
          unzip ./hoprd-sdk-python.zip -d ./hoprd-sdk-python && rm hoprd-sdk-python.zip
          patch ./hoprd-sdk-python/hoprd_sdk/api_client.py ./scripts/python-sdk.patch

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
            token: ${{ secrets.GH_RUNNER_TOKEN }}
            path: ./hoprd-sdk-python
            commit-message: "Update SDK Python to version ${{ steps.setup.outputs.current_version }}"
            title: "Bump SDK to ${{ steps.setup.outputs.current_version }}"
            body-path: .github/files/pr-python-sdk.md
            branch: bot/bump-${{ steps.setup.outputs.current_version }}
            delete-branch: true
            assignees: ${{ github.actor }}
            team-reviewers: "@hoprnet/hopr-development"

      - name: Enable Auto Merge
        run: |
            git fetch
            git checkout bot/bump-${{ steps.setup.outputs.current_version }}
            gh pr merge --auto --delete-branch --squash
        env:
          GH_TOKEN: ${{ secrets.GH_RUNNER_TOKEN }}
